### ISSUE TITLE
Offline generation of XR/XRC CRDs from the XRD

### ISSUE THREAD

**Issue by Chewie** [upbound/upbound#1]
### What problem are you facing?

While crossplane tooling itself never needs the XR/XRC CRDs on-disk, plenty of tools in the wider k8s ecosystem need to parse those CRD for some sort of generation (bindings, documentation, web ui forms...), and don't accept XRDs.

Currently, the only way to get those CRDs is to actually feed the XRD to a running cluster and query them back.

### How could Upbound help solve your problem?

A command like `up crds generate` could write out the two CRDs on-disk from an single yaml/whole folder input, facilitating the process of then feeding those CRDs to something else e.g during CI.

**Comment by hl782** [comment]
Hi Chewie, thanks for your feedback. Unfortunately, this is something that we on the product team do not want to expose with the Up CLI tooling at this time.

**Comment by haarchri** [comment]
this will be included in v0.42.0 up-cli release
if you want to test it before the release: https://cli.upbound.io/releases?prefix=build/v0.42.0-0.rc.0-320-g5d329f16/
